// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBoZUt0n955_Jse6ATJg5aCKzA5-e8IVN8',
    appId: '1:662719735520:web:ea53339e16da13a4b51285',
    messagingSenderId: '662719735520',
    projectId: 'my-firebase-project-4b6a5',
    authDomain: 'my-firebase-project-4b6a5.firebaseapp.com',
    storageBucket: 'my-firebase-project-4b6a5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOQrtwz4pRFtQRd5OhOnMIEpM8PRGLGwQ',
    appId: '1:662719735520:android:3a4fe9734023bf63b51285',
    messagingSenderId: '662719735520',
    projectId: 'my-firebase-project-4b6a5',
    storageBucket: 'my-firebase-project-4b6a5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmEGchJu99x_W3wrNwAxMFiH21UDtLURU',
    appId: '1:662719735520:ios:2bbbe28f26db11dcb51285',
    messagingSenderId: '662719735520',
    projectId: 'my-firebase-project-4b6a5',
    storageBucket: 'my-firebase-project-4b6a5.appspot.com',
    iosClientId: '662719735520-kbfa13k7d787597pisamnjq449f82o74.apps.googleusercontent.com',
    iosBundleId: 'com.example.modernlogintute',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmEGchJu99x_W3wrNwAxMFiH21UDtLURU',
    appId: '1:662719735520:ios:2bbbe28f26db11dcb51285',
    messagingSenderId: '662719735520',
    projectId: 'my-firebase-project-4b6a5',
    storageBucket: 'my-firebase-project-4b6a5.appspot.com',
    iosClientId: '662719735520-kbfa13k7d787597pisamnjq449f82o74.apps.googleusercontent.com',
    iosBundleId: 'com.example.modernlogintute',
  );
}
